--liquibase formatted sql
--changeset Kostyantyn.Panchenko:2017-01-22-01

INSERT INTO visitors(id, name, password, email, created) VALUES(1, 'superuser', 'Super:P4ssw0rd', 'yougetit@ukr.net', '1983-04-26 05:55:00');
INSERT INTO visitors(id, name, password, email, created) VALUES(2, 'admin', 'admin', 'youget@ukr.net', '1983-04-26 05:55:00');
INSERT INTO visitors(id, name, password, email, created) VALUES(3, 'Jim Beam', 'jimbeam', 'jimbeam@ukr.net', '1983-04-26 05:55:00');
INSERT INTO visitors(id, name, password, email, created) VALUES(4, 'Jose Cuervo', 'josecuervo', 'josecuervo@ukr.net', '1983-04-26 05:55:00');
INSERT INTO visitors(id, name, password, email, created) VALUES(5, 'Sovignon Blank', 'sovignonblanc', 'sovignonblanc@ukr.net', '1983-04-26 05:55:00');

INSERT INTO posts(id, title, content, country, region, city, created, image_id) VALUES(1, 'When the sun is on your side', 'Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.', 'Sweden', 'Stockholm County', 'Stockholm', '2016-08-20 12:00:00', 1);
INSERT INTO posts(id, title, content, country, region, city, created, image_id) VALUES(2, 'Кожному своє', 'Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.', 'Poland', 'Lesser Poland Voivodeship', 'Krakow', '2016-06-27 12:00:00', 2);
INSERT INTO posts(id, title, content, country, region, city, created, image_id) VALUES(3, 'Краків. Магазин музичних мініатюр.', 'Архітектурна втеча на вихідні. Так виглядав чорновий варіант Кракова – першої мандрівки Польщею. Потім, вже з квитками на руках, я дивилась варіанти добирання з аеропорту Катовіце до Кракова і зрозуміла, що по дорозі можна заїхати до Аушвіца. Для загального розвитку. Для більшої ж атмосферності вирішила прочитати “Список Шиндлера” і поділилась задумом з татом. Тато вислухав і сказав:
Може не треба Освєнцима? Бо потім у Кракові всюди буде Освєнцим.
Ці слова звучали в унісон моїм відчуттям, тому я не просто викреслила з програми Аушвіц, а вирішила й до фабрики Шиндлера не ходити: все життя моя допитливість амортизується негативною енергетикою місць масової смерті.
У понеділок йшов дощ, я гуляла без мапи і натрапила на квартал із шестикутними зірками на будинках… “От тобі й Освєнцим без Освєнцима”, – подумалось тоді, а далі кожен мій крок і погляд малювали вуличні історії 40-х років минулого століття.
Наприклад, про сім’ю музикантів, які навесні 1943-го року спакували свої інструменти з впевненістю про переїзд, і попрямували на масову страту, а дивом вцілілий хлопчик чи, можливо, дівчинка в червоному пальто зберегли в пам’яті образ музикантів і по поверненні до відновленого Кракова заснували цей магазин музичних мініатюр.', 'Польща', NULL, 'Краків', '2016-11-09 12:00:00', 3);
INSERT INTO posts(id, title, content, country, region, city, created, image_id) VALUES(4, 'Париж за 5 днів. Практичний. Туристичний.', 'Щоб побачити Париж потрібно щонайменше два тижні (якщо ви вважаєте інакше, то у нас просто різні потреби і відчуття міста). Але цього часу, у тих, хто просив написати про Париж, як правило, нема, тому амбітно вкладаю мій особистий оптимум у 5 днів. Літаки і транспорт в місті. <p>З Києва до Парижа (аеропорт Шарль де Голь) є кілька прямих рейсів і кілька з пересадкою. Мій улюблений прямий – Airfrance (власний досвід був лише з ними),  а з пересадкою – KLM. Перші зручні тим, що можна вилетіти зранку туди і ввечері назад, тим самим отримавши додатковий час в Парижі. Других я колись зацінила через економію часу: у Парижі можна застрягнути на годину (й більше) на паспортному контролі, в Амсті ж він проходиться за годину трансферу, а потім в Парижі ви одразу виходите в місто. Звісно, є ризик не встигнути на трансфер в Амсті.
<p>Про потяг: 10 євро і приблизно година дороги з 2-3-ма пересадками, залежно від вашого пункту призначення в самому Парижі. <p>Оскільки мене просили написати про оптимальний варіант, то поясню тут чому 5 днів “оптимальні”: є проїзний Navigo, вартість на 5 днів 25 євро. Покриває міський метрополітен і 5 зон паризького транспорту. Тобто 25 євро окупаються вже на вартості аеропорт-місто-аеропорт (двічі по 10 євро = 20 євро) і кілька подорожей на метро (1 поїздка = 1,80 євро). Я цією опцією не користувалась з різних причин, але всі знайомі беруть її на різну кількість днів і задоволені. КВИТКИ треба обов’язково компостувати і зберігати до кінця поїздки, бо вони потрібні для виходу зі станцій. Про Navigo не знаю, але має знати інтернет.', 'Франція', NULL, 'Париж', '2016-12-26 12:00:00', 4);
INSERT INTO posts(id, title, content, country, region, city, created, image_id) VALUES(5, 'Орден за віру в людство', 'Це фото зробив незнайомець у Гданську. Незнайомця мені “подарувало” польське консульство, вімовивши його друзям у візі. Так Саша полетів сам до Гданська, а в Жулянах познайомився зі мною і запропонував гуляти разом.
 <p>Удвох ми розбирались з квитками на потяг в аеропорту Леха Валенси, селили один одного в готель (наші готелі були на відстані 200 метрів), плутались у польському меню, пили імбирний чай на Балтійському морі і годували лебедів у Сопоті. Потім Саша полетів до Варшави, а я поїхала до Оліви й гданських бастіонів.
 Саша показав тисячу і одну перевагу айфонів, розказав про гоупро і функціональне призначення “маятникових гирьок” (не знаю, як їх правильно назвати) на старих будівлях і ще багато чого. А після того, як на другий день знайомства я залишила йому всі речі включно з гаманцем, документами і телефоном (бо нести це все в туалет було незручно), купив мені цукерку.
 <p>– За віру в людство, – сказав Саша,  а цей кадр назвав “маленька Юля і великі Лебеді”.', 'Польща', NULL, 'Гданськ', '2017-01-10 12:00:00', 5);

INSERT INTO images(id) VALUES(1);
INSERT INTO images(id) VALUES(2);
INSERT INTO images(id) VALUES(3);
INSERT INTO images(id) VALUES(4);
INSERT INTO images(id) VALUES(5);

INSERT INTO comments(id, content, author_id, post_id, created) VALUES(1, 'Fantastic story!', 3, 1, '2017-01-22 14:04:56');
INSERT INTO comments(id, content, author_id, post_id, created) VALUES(2, 'You should visit Mexico :)', 4, 1, '2017-01-22 14:08:23');
